export const navMenuList = ["Profile", "Rules", "About", "Login"]

export const buttonObject = {
  "P1" :"Winner",
  "P2" :"Second",
  "P3" :"Third",
  "P4" :"Fourth",
  "P5" :"Fifth",
  "P6" :"Sixth",
  "P7" :"Seventh",
  "P8" :"Eighth",
  "P9" :"Ninth",
  "P10" :"Tenth",
  "Pole" : "Pole Position",
  "DotD" : "Driver of the Day",
  "FL" : "Fastest Lap",
  "MPG" : "Most Positions Gained",
  "BFL" : "Best First Lap"
}

export const buttonsStringsObject = {
  "P1" :"Winner",
  "P2" :"Second",
  "P3" :"Third",
  "P4" :"Fourth",
  "P5" :"Fifth",
  "P6" :"Sixth",
  "P7" :"Seventh",
  "P8" :"Eighth",
  "P9" :"Ninth",
  "P10" :"Tenth",
  "Pole" : "Pole Position",
  "PoleT" : "Pole Lap Time",
  "DotD" : "Driver of the Day",
  "Fastest" : "Fastest Lap",
  "MPG" : "Most Positions Gained",
  "BFL" : "Best First Lap",
  "Race": "Race Event"
}
export const driversObject = {
  "Sebastien Vettel":"Vettel",
  "Charles Leclerc":"Leclerc",
  "Romain Grosjean":"Grosjean",
  "Kevin Magnussen":"Magnussen",
  "Lando Norris":"Norris",
  "Carlos Sainz":"Sainz",
  "Lewis Hamilton":"Hamilton",
  "Valtteri Bottas":"Bottas",
  "Sergio Perez":"Perez",
  "Lance Stroll":"Stroll",
  "Pierre Gasly":"Gasly",
  "Max Verstappen":"Verstappen",
  "Daniel Ricciardo":"Ricciardo",
  "Nico Hulkenberg":"Hulkenberg",
  "Jimi Raikkonen":"Raikkonen",
  "Antonio Giovinazzi":"Giovinazzi",
  "Alexander Albon":"Albon",
  "Daniel Kyvat":"Kyvat",
  "George Russell":"Russell",
  "Robert Kubica":"Kubica"
}

export const driversHidden = {
  "Vettel" : false,
  "Leclerc" : false,
  "Grosjean" : false,
  "Magnussen" : false,
  "Norris" : false,
  "Sainz" : false,
  "Hamilton" : false,
  "Bottas" : false,
  "Perez" : false,
  "Stroll" : false,
  "Gasly" : false,
  "Verstappen" : false,
  "Ricciardo" : false,
  "Hulkenberg" : false,
  "Raikkonen" : false,
  "Giovinazzi" : false,
  "Albon" : false,
  "Kyvat" : false,
  "Russell" : false,
  "Kubica" : false
}
export const driversNotHidden = {
  "Vettel" : false,
  "Leclerc" : false,
  "Grosjean" : false,
  "Magnussen" : false,
  "Norris" : false,
  "Sainz" : false,
  "Hamilton" : false,
  "Bottas" : false,
  "Perez" : false,
  "Stroll" : false,
  "Gasly" : false,
  "Verstappen" : false,
  "Ricciardo" : false,
  "Hulkenberg" : false,
  "Raikkonen" : false,
  "Giovinazzi" : false,
  "Albon" : false,
  "Kyvat" : false,
  "Russell" : false,
  "Kubica" : false
}
export const defaultPredictions = {
  P1:null,
  P2:null,
  P3:null,
  P4:null,
  P5:null,
  P6:null,
  P7:null,
  P8:null,
  P9:null,
  P10:null,
  Pole:null,
  PoleT:null,
  DotD:null,
  Fastest:null,
  MPG:null,
  BFL:null,
  Race : null
};
